version: 2
jobs:
  build:
    docker:
      - image: flauc/firebase
    environment:
      NPM_VERSION: "6.9.0"
    steps:
      - run:
          name: Set Private Environment
          command: firebase functions:config:set sendgrid.token=$SENDGRID_TOKEN email.from=$EMAIL_FROM googleapi.client_id=$GOOGLE_CLIENT_ID googleapi.client_secret=$GOOGLE_CLIENT_SECRET googleapi.sheet_id=$GOOGLE_SHEET_ID --project=jaspero-sheets --token $FIREBASE_CI_TOKEN
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}-{{ checksum "functions/package-lock.json" }}
      - run:
        name: Where
        command: ls
      - run:
          name: Install Shared dependencies
          command: yes | npm ci || true
      - run:
          name: Install Function dependencies
          command: yes | npm --prefix functions ci || true
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}-{{ checksum "functions/package-lock.json" }}
          paths:
            - node_modules
            - functions/node_modules
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Building
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                npm run build
            fi
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - package.json
            - functions/package.json
            - package-lock.json
            - firebase.json
            - functions/node_modules
            - functions/dist
            - functions/lib
            - firestore.rules
            - .firebaserc
  deploy:
    docker:
      - image: flauc/firebase
    steps:
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Deploy Master to Firebase
          command: npm run deploy  -- -m $CIRCLE_SHA1 --token $FIREBASE_CI_TOKEN

workflows:
  version: 2
  -deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
